// Single source of truth for the inflatable catalogue, imported from the
// existing WooCommerce export and tidied up. Used by prisma/seed.ts and by the
// admin "Load starter catalogue" action. Owner can edit everything in /admin.
// Prices are in pence. The Bluetooth Speaker is an add-on (seeded inactive).

export interface CatalogueItem {
  name: string;
  slug: string;
  description: string;
  theme: string | null;
  dimensions: string | null;
  ageSuitability: string | null;
  pricePerDay: number | null;
  images: string[];
  active: boolean;
  sortOrder: number;
}

export const CATALOGUE: CatalogueItem[] = [
  {
    name: "Spider-Man Castle",
    slug: "spider-man-castle",
    description: "A bright Spider-Man themed bouncy castle that is perfect for superhero parties and energetic younger children. A great all-round option for gardens, parties and local events.",
    theme: "Superhero",
    dimensions: null,
    ageSuitability: "Up to 12 years",
    pricePerDay: 8000,
    images: ["https://jumpingjacksleeds.co.uk/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-07-at-12.55.211.jpeg"],
    active: true,
    sortOrder: 1,
  },
  {
    name: "Super Hero's Castle",
    slug: "super-hero-s-castle",
    description: "A fun superhero themed bouncy castle with bold colours and a side slide section, ideal for children who want something more exciting than a standard castle. Great for birthdays, school events and family parties.",
    theme: "Superhero",
    dimensions: null,
    ageSuitability: "Up to 12 years",
    pricePerDay: 8000,
    images: ["https://jumpingjacksleeds.co.uk/wp-content/uploads/2026/03/WhatsApp-Image-2026-04-15-at-21.04.46.jpeg"],
    active: true,
    sortOrder: 2,
  },
  {
    name: "Sea-Life Castle",
    slug: "sea-life-castle",
    description: "A colourful sea-life themed bouncy castle with an under-the-sea design that works well for younger children. A popular choice for mixed parties and general children's entertainment.",
    theme: "Sea Life",
    dimensions: null,
    ageSuitability: "Up to 12 years",
    pricePerDay: 8000,
    images: ["https://jumpingjacksleeds.co.uk/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-07-at-12.55.212.jpeg"],
    active: true,
    sortOrder: 3,
  },
  {
    name: "Frozen Castle",
    slug: "frozen-castle",
    description: "A Frozen themed inflatable that is ideal for princess parties and younger children who love character-themed inflatables. Bright, eye-catching and well suited to birthdays and indoor or outdoor use where space allows.",
    theme: "Princess",
    dimensions: null,
    ageSuitability: "Up to 12 years",
    pricePerDay: 8000,
    images: ["https://jumpingjacksleeds.co.uk/wp-content/uploads/2026/03/WhatsApp-Image-2026-04-15-at-21.04.322.jpeg"],
    active: true,
    sortOrder: 4,
  },
  {
    name: "Tik Tok Castle",
    slug: "tik-tok-castle",
    description: "A Tik Tok themed bouncy castle designed for younger children. A simple and popular option for birthday parties, family gatherings and smaller events.",
    theme: "Disco",
    dimensions: null,
    ageSuitability: "Up to 12 years",
    pricePerDay: 12000,
    images: ["https://jumpingjacksleeds.co.uk/wp-content/uploads/2026/03/WhatsApp-Image-2026-04-15-at-21.04.39.jpeg"],
    active: true,
    sortOrder: 5,
  },
  {
    name: "Pink / Purple Castle",
    slug: "pink-purple-castle",
    description: "A classic pink and purple bouncy castle that is perfect for birthdays, family celebrations and general children's parties. Velcro theme attachments may be available on request, making it a flexible option for different party themes.",
    theme: "Girls",
    dimensions: null,
    ageSuitability: "Up to 12 years",
    pricePerDay: 8000,
    images: ["https://jumpingjacksleeds.co.uk/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-07-at-12.55.20.jpeg"],
    active: true,
    sortOrder: 6,
  },
  {
    name: "Nerf Battle Zone",
    slug: "nerf-battle-zone",
    description: "An interactive Nerf themed inflatable game that is great for competitive fun at children's parties and events. Supplied with Nerf guns, making it a good add-on or lower-cost standalone hire option.",
    theme: "Nerf",
    dimensions: null,
    ageSuitability: "Ages 5+",
    pricePerDay: 7000,
    images: ["https://jumpingjacksleeds.co.uk/wp-content/uploads/2026/03/WhatsApp-Image-2026-04-15-at-21.04.43.jpeg"],
    active: true,
    sortOrder: 7,
  },
  {
    name: "Barbie Castle",
    slug: "barbie-castle",
    description: "A bright pink Barbie-themed disco castle that's a dream come true for fans of all things pink and sparkly. A standout choice for birthday parties and a guaranteed hit with younger children.",
    theme: "Princess",
    dimensions: null,
    ageSuitability: "Up to 12 years",
    pricePerDay: 12000,
    images: ["https://jumpingjacksleeds.co.uk/wp-content/uploads/2026/03/WhatsApp-Image-2026-04-15-at-21.04.41.jpeg"],
    active: true,
    sortOrder: 8,
  },
  {
    name: "Party Time Slide / Disco Combo",
    slug: "party-time-slide-disco-combo",
    description: "A party-themed inflatable combo unit with bouncing area and front slide, designed to give children more to do than a standard castle. Includes disco ball and speaker / Bluetooth speaker, making it ideal for lively birthday parties.",
    theme: "Disco",
    dimensions: null,
    ageSuitability: "Up to 12 years",
    pricePerDay: 12000,
    images: ["https://jumpingjacksleeds.co.uk/wp-content/uploads/2026/03/WhatsApp-Image-2026-04-15-at-21.04.33.jpeg"],
    active: true,
    sortOrder: 9,
  },
  {
    name: "K Pop Disco Castle",
    slug: "k-pop-disco-castle",
    description: "A pink and purple combo castle with slide, offering both bounce and slide fun in one inflatable. Includes Bluetooth speaker and disco ball, and theme artwork can be added on selected hires.",
    theme: "Disco",
    dimensions: null,
    ageSuitability: "Up to 12 years",
    pricePerDay: 12000,
    images: ["https://jumpingjacksleeds.co.uk/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-07-at-12.55.20.jpeg"],
    active: true,
    sortOrder: 10,
  },
  {
    name: "Purple Bounce and Slide Package",
    slug: "purple-bounce-and-slide-package",
    description: "A larger package option combining a purple bounce castle and matching purple slide for bigger parties or where more than one inflatable is wanted. Ideal for larger birthdays, family parties and events where children of different ages will be attending.",
    theme: "Slide & Bounce",
    dimensions: null,
    ageSuitability: "Up to 12 years",
    pricePerDay: 17500,
    images: ["https://jumpingjacksleeds.co.uk/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-07-at-12.55.07.jpeg"],
    active: true,
    sortOrder: 11,
  },
  {
    name: "Red / Black Mega Slide",
    slug: "red-black-mega-slide",
    description: "A tall inflatable slide in bold red and black colours, perfect for bigger parties, events and children who want a more exciting feature inflatable. A standout piece that works well as the main attraction.",
    theme: "Slide & Bounce",
    dimensions: null,
    ageSuitability: "Up to 12 years",
    pricePerDay: 20000,
    images: ["https://jumpingjacksleeds.co.uk/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-07-at-12.55.221.jpeg"],
    active: true,
    sortOrder: 12,
  },
  {
    name: "Dragon Castle with Slide",
    slug: "dragon-castle-with-slide",
    description: "A themed dragon inflatable with bounce area and attached slide, giving children a more adventurous and eye-catching party option. Great for birthdays, fun days and events where you want something a little different.",
    theme: "Adventure",
    dimensions: null,
    ageSuitability: "Up to 12 years",
    pricePerDay: 14000,
    images: ["https://jumpingjacksleeds.co.uk/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-07-at-12.55.22.jpeg"],
    active: true,
    sortOrder: 13,
  },
  {
    name: "10ft Hyper Slide",
    slug: "10ft-hyper-slide",
    description: "A big 10ft inflatable slide that brings the wow factor to any party or event. Great fun for children of all ages and a brilliant centrepiece when you want something more exciting than a standard castle.",
    theme: "Slide & Bounce",
    dimensions: null,
    ageSuitability: "Up to 12 years",
    pricePerDay: 15000,
    images: ["https://jumpingjacksleeds.co.uk/wp-content/uploads/2026/03/WhatsApp-Image-2026-04-15-at-21.04.36.jpeg", "https://jumpingjacksleeds.co.uk/wp-content/uploads/2026/03/WhatsApp-Image-2026-04-15-at-21.04.36.jpeg"],
    active: true,
    sortOrder: 14,
  },
  {
    name: "Disco Dome With Slide",
    slug: "disco-dome-with-slide",
    description: "An enclosed disco dome with a built-in slide, complete with space to bounce and dance. Ideal for music-loving kids and lively parties, day or night.",
    theme: "Disco",
    dimensions: null,
    ageSuitability: "Up to 12 years",
    pricePerDay: 15000,
    images: ["https://jumpingjacksleeds.co.uk/wp-content/uploads/2026/03/WhatsApp-Image-2026-04-15-at-21.04.34.jpeg", "https://jumpingjacksleeds.co.uk/wp-content/uploads/2026/03/WhatsApp-Image-2026-04-15-at-21.04.336.jpeg"],
    active: true,
    sortOrder: 15,
  },
  {
    name: "Dance and Bounce Adult Castle",
    slug: "dance-and-bounce-adult-castle",
    description: "A large, sturdy castle built for grown-ups — perfect for adult birthdays, hen and stag parties and garden events. Comes with a Bluetooth speaker so you can bring your own soundtrack.",
    theme: "Adult",
    dimensions: null,
    ageSuitability: "Teens & adults",
    pricePerDay: 12000,
    images: ["https://jumpingjacksleeds.co.uk/wp-content/uploads/2026/03/WhatsApp-Image-2026-04-15-at-21.04.343.jpeg"],
    active: true,
    sortOrder: 16,
  },
  {
    name: "My Little Pony Castle",
    slug: "my-little-pony-castle",
    description: "A colourful My Little Pony themed children's castle, full of friendly characters and bright colours. Perfect for younger children's birthday parties and a firm favourite with pony fans.",
    theme: "Character",
    dimensions: null,
    ageSuitability: "Up to 12 years",
    pricePerDay: 8000,
    images: ["https://jumpingjacksleeds.co.uk/wp-content/uploads/2026/03/WhatsApp-Image-2026-04-15-at-21.04.335.jpeg"],
    active: true,
    sortOrder: 17,
  },
  {
    name: "Party Time Kids Slide",
    slug: "party-time-kids-slide",
    description: "A fun, kid-sized inflatable slide that's perfect for younger children. Safe, colourful and endlessly re-rideable — a great addition to any birthday party.",
    theme: "Slide & Bounce",
    dimensions: null,
    ageSuitability: "Up to 12 years",
    pricePerDay: 9000,
    images: ["https://jumpingjacksleeds.co.uk/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-15-at-21.04.352.jpeg"],
    active: true,
    sortOrder: 18,
  },
  {
    name: "10ft Slide and Nerf Package",
    slug: "10ft-slide-and-nerf-package",
    description: "Our big-value package combining the 10ft Hyper Slide with the Nerf Battle Zone — slides and target games in one booking. Ideal for bigger parties and mixed age groups who want plenty to do.",
    theme: "Nerf",
    dimensions: null,
    ageSuitability: "Ages 5+",
    pricePerDay: 20000,
    images: ["https://jumpingjacksleeds.co.uk/wp-content/uploads/2026/03/WhatsApp-Image-2026-04-15-at-21.04.371.jpeg"],
    active: true,
    sortOrder: 19,
  },
  {
    name: "Party Time and Nerf Package",
    slug: "party-time-and-nerf-package",
    description: "A great-value package pairing the Party Time slide combo with the Nerf Battle Zone, giving children bouncing, sliding and competitive Nerf fun all in one. Perfect for larger celebrations.",
    theme: "Nerf",
    dimensions: null,
    ageSuitability: "Ages 5+",
    pricePerDay: 17000,
    images: ["https://jumpingjacksleeds.co.uk/wp-content/uploads/2026/03/WhatsApp-Image-2026-04-15-at-21.04.33.jpeg", "https://jumpingjacksleeds.co.uk/wp-content/uploads/2026/03/WhatsApp-Image-2026-04-15-at-21.04.43.jpeg"],
    active: true,
    sortOrder: 20,
  },
  {
    name: "Bluetooth Speaker",
    slug: "bluetooth-speaker",
    description: "Add-on only — must be hired alongside a castle. A portable Bluetooth speaker so you can play your own party playlist through the day.",
    theme: "Add-on",
    dimensions: null,
    ageSuitability: null,
    pricePerDay: 2000,
    images: ["https://jumpingjacksleeds.co.uk/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-15-at-21.40.34.jpeg"],
    active: false,
    sortOrder: 21,
  },
];

export const CANCELLATION_POLICY = "Plans change — here's how cancellations work.\n\nCancel or reschedule free of charge with 48 hours' notice or more.\n\nFor cancellations within 48 hours of your hire date we're unable to offer a refund, as we will usually have turned other bookings away for that day. You're welcome to reschedule to another available date subject to availability.\n\nWeather: for everyone's safety we can't operate inflatables in high winds (gusts above roughly 24mph) or heavy rain. If we need to cancel for safety reasons, you can reschedule for free or receive a full refund.";
